name: 🔥 Fire Risk Daily Pipeline

on:
  schedule:
    - cron: "0 18 * * *"  
  workflow_dispatch:     

jobs:
  run-r-script:
    runs-on: ubuntu-latest

    env:
      TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
      TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      VIIRS_KEY: ${{ secrets.VIIRS_KEY }}
      CDS_API_KEY: ${{ secrets.CDS_API_KEY }}
      CDS_USER_ID: ${{ secrets.CDS_USER_ID }}

    steps:
      - name: 🔽 Клонирование репозитория
        uses: actions/checkout@v4

      - name: Установка Git LFS
        run: |
          git lfs install
          git lfs pull

      - name: 🛠️ Установка R
        uses: r-lib/actions/setup-r@v2

      - name: 📦 Установка зависимостей
        run: |
          Rscript -e 'install.packages(c("ecmwfr", "tidyverse", "stars", "openair", "httr", "lubridate", "osmdata", "sf", "leaflet", "geosphere", "mapview", "htmlwidgets", "webshot", "ggplot2", "rmarkdown", "curl", "xml2"))'
          Rscript -e 'webshot::install_phantomjs()'

      - name: 🚀 Запуск основного R-скрипта
        run: Rscript pipeline.R

      - name: Создание папки для вывода
        run: mkdir -p output

      - name: 📤 Загрузка артефактов (например, PNG-карт)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: output-plots
          path: output/
