name: 🔥 Fire Risk Daily Pipeline

on:
  schedule:
    - cron: "0 11 * * *"  # каждый день в 14:00 по МСК
  workflow_dispatch:

jobs:
  run-r-script:
    runs-on: ubuntu-latest

    env:
      TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
      TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      VIIRS_KEY: ${{ secrets.VIIRS_KEY }}
      CDS_API_KEY: ${{ secrets.CDS_API_KEY }}
      CDS_USER_ID: ${{ secrets.CDS_USER_ID }}
      R_LIBS_USER: ~/R/Library

    steps:
      - name: 🔽 Клонирование репозитория
        uses: actions/checkout@v4

      - name: 🛠️ Установка R
        uses: r-lib/actions/setup-r@v2

      - name: 📦 Кэширование библиотек R
        uses: actions/cache@v3
        with:
          path: ~/R/Library
          key: ${{ runner.os }}-r-${{ hashFiles('**/*.R', '**/*.Rmd', '**/DESCRIPTION') }}
          restore-keys: |
            ${{ runner.os }}-r-

      - name: 🔧 Установка системных библиотек
        run: |
          sudo apt-get update
          sudo apt-get install -y \
          libcurl4-openssl-dev libssl-dev libxml2-dev \
          libudunits2-dev libgdal-dev libgeos-dev libproj-dev \
          libfontconfig1-dev \
          libharfbuzz-dev libfreetype6-dev \
          libfribidi-dev

      - name: 📦 Установка зависимостей и запуск
        run: |
          mkdir -p ~/R/Library
          export R_LIBS_USER=~/R/Library

          echo "👉 Устанавливаю критические зависимости"
          Rscript -e 'install.packages(c("curl", "httr"), repos = "https://cloud.r-project.org")'

          echo "👉 Устанавливаю ecmwfr"
          Rscript -e 'install.packages("ecmwfr", repos = "https://cloud.r-project.org")'
          Rscript -e 'library(ecmwfr); print("✅ ecmwfr загружен успешно!")'

          echo "👉 Устанавливаю остальные зависимости"
          Rscript -e 'install.packages(c(
            "tidyverse", "stars", "openair", "lubridate", 
            "osmdata", "sf", "leaflet", "geosphere", "mapview", "htmlwidgets", 
            "webshot", "ggplot2", "rmarkdown", "xml2"
          ), repos = "https://cloud.r-project.org")'

          echo "👉 Устанавливаю PhantomJS"
          Rscript -e 'webshot::install_phantomjs()'

          echo "🚀 Запуск скрипта обработки"
          Rscript Scripts/pipeline.R

      - name: 🔍 Проверка установленных пакетов
        run: |
          export R_LIBS_USER=~/R/Library
          Rscript -e 'print(installed.packages()[, "Package"])'

      - name: 📂 Просмотр содержимого папки output/
        run: ls -lh output/ || echo "Нет папки output/"

      - name: 📤 Загрузка артефактов (output/)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: output-plots
          path: output/
          if-no-files-found: warn
