name: 🔥 Fire Risk Daily Pipeline

on:
  schedule:
    - cron: "0 11 * * *"   # запуск каждый день в 14:00 UTC
  workflow_dispatch:       # запуск вручную

jobs:
  run-r-script:
    runs-on: ubuntu-latest

    env:
      TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
      TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      VIIRS_KEY: ${{ secrets.VIIRS_KEY }}
      CDS_API_KEY: ${{ secrets.CDS_API_KEY }}
      CDS_USER_ID: ${{ secrets.CDS_USER_ID }}

    steps:
      - name: 🔽 Checkout repository
        uses: actions/checkout@v4

      - name: Установка R
        uses: r-lib/actions/setup-r@v2

      - name: 📦 Кэширование пакетов
        uses: actions/cache@v3
        with:
          path: ${{ env.R_LIBS_USER }}
          key: ${{ runner.os }}-r-packages-${{ hashFiles('**/*.R', '**/*.Rmd') }}
          restore-keys: |
            ${{ runner.os }}-r-packages-

      - name: Установка зависимостей R
        run: |
          install.packages(c("ecmwfr", "tidyverse", "stars", "openair", "httr", "lubridate",
                             "osmdata", "sf", "leaflet", "geosphere", "mapview", "htmlwidgets",
                             "webshot", "ggplot2", "rmarkdown", "curl", "xml2"))
          webshot::install_phantomjs()

      - name: Запуск R-скрипта
        run: |
          Rscript -e 'source("pipeline.R"); main()'

      - name: 📂 Показать содержимое output/ (для отладки)
        run: ls -l output/

      - name: 📤 Загрузка артефактов output
        uses: actions/upload-artifact@v4
        with:
          name: output-plots
          path: output/
          if-no-files-found: warn
